feat: unsubscribe user from marketing emails
MultiEmail/backend pull request #196
Opened 2022-11-08 05:13 UTC by aayushchugh

### Description

New route to unsubscribe email

### Checklist:

-   [ ] This pull request follow our contribution guidelines
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (postman and wiki)
-   [ ] I have written tests for the code
-   [ ] I have updated .env.example file for new .env variables

Closes #159 

### What is new behavior?

![image](https://user-images.githubusercontent.com/69336518/200480615-59843902-f347-42b5-bff7-7ccf298bc2a6.png)

### Breaking Changes?

Need new .env variable `BASE_URL`

2022-11-08 06:10 UTC, tharun634 requested changes

2022-11-08 06:10 UTC, tharun634 commented on src/routes/user.routes.ts
> +//
```suggestion
 *
```

2022-11-08 06:10 UTC, tharun634 commented on src/schemas/user.schema.ts
> + * This schema is used to validate `POST /users/:id/marketing-emails/unsubscribe` request
```suggestion
 * This schema is used to validate `GET /users/:id/marketing-emails/unsubscribe` request
```

2022-11-08 06:10 UTC, tharun634 commented on src/schemas/user.schema.ts
> +export const unsubscribeUserFromMarketingEmailSchema = z.object({
```suggestion
export const getUnsubscribeUserFromMarketingEmailSchema = z.object({
```

Not sure if we should do this, just to stay consistent

2022-11-08 12:32 UTC, is-it-ayush approved these changes
Good Code Ayush!! I'll merge with once the requested changes are made.

2022-11-13 13:20 UTC, tharun634 approved these changes

2022-11-18 10:52 UTC, merged