Add test execution on Pull Request
MultiEmail/backend pull request #98
Opened 2022-10-06 17:48 UTC by alberturria

### Description

Added a new github action workflow, so we ensure that the tests are run on pull request.

**Dependency**:
I've seen that there are at least a couple of sensitive environment variables that are hardcoded in the repo. That's why I'm making usage of the [encripted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) within the workflow.
⚠️ This means that these needs to be added as a secret to the github project ⚠️ 
### Checklist:

- [x] This pull request follow our contribution guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (postman and swagger)
- [x] I have written tests for the code
- [x] I have updated .env.example file for new .env variables

### What is current behavior?

N/A

Closes #95

### What is new behavior?

The tests are ran on PR.

### Breaking Changes?

N/A

### Additional information

N/A

2022-10-06 17:51 UTC, aayushchugh requested changes

2022-10-06 17:51 UTC, aayushchugh commented on .github/workflows/tests.yml
> +      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
Please include another env variables too

They are mentioned in `.env.example`

2022-10-06 17:51 UTC, aayushchugh commented on .github/workflows/tests.yml
> +      - run: npm t
Use `yarn test` command to run tests

2022-10-06 18:02 UTC, alberturria commented on .github/workflows/tests.yml
> +      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
Sure! ✅

2022-10-06 18:02 UTC, alberturria commented on .github/workflows/tests.yml
> +      - run: npm t
Changed! 👍

2022-10-06 18:02 UTC, aayushchugh approved these changes

2022-10-06 18:04 UTC, aayushchugh commented
@alberturria I will merge this once you mark this PR as `Ready for Review`

2022-10-06 18:05 UTC, alberturria commented
> @alberturria I will merge this once you mark this PR as `Ready for Review`

Great! it should be no longer marked as draft 🙂

2022-10-06 18:08 UTC, aayushchugh commented
@alberturria will merge this PR tomorrow morning

2022-10-06 20:43 UTC, merged

2022-10-07 05:17 UTC, aayushchugh commented
@all-contributors please add @alberturria for code